name: Test drift detector on empty resource
on:
  pull_request:

env:
  OPEN_TOFU_VERSION: 1.10.5
  TERRAFORM_VERSION: 1.9.8
  TERRAGRUNT_VERSION: 0.68.6
  TF_SUMMARIZE_VERSION: 0.3.5

jobs:
  drift-detector-empty-resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@5f76a50c0b5f0e133634fecc8dd42f67db57bc05 # v1.1.0

      - name: Run drift detection on empty resource
        id: drift-detect
        uses: ./
        with:
          directory: test/drift-detect
          allow-failure: false
          comment: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post drift data to Slack
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.slack_webhook_url }}
          webhook-type: incoming-webhook
          payload: >
            {"text":"Terraform drift for ${{ github.event.repository.name }} (${{ matrix.name }}): status=${{ fromJson(steps.drift-detect.outputs.drift-output).status }}, created=${{ join(fromJson(steps.drift-detect.outputs.drift-output).resources.created, ', ') || 'none' }}, updated=${{ join(fromJson(steps.drift-detect.outputs.drift-output).resources.updated, ', ') || 'none' }}, deleted=${{ join(fromJson(steps.drift-detect.outputs.drift-output).resources.deleted, ', ') || 'none' }}"}

